"""create clear data base

Revision ID: 383497a7ec70
Revises: 
Create Date: 2026-05-23 11:06:39.112445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383497a7ec70'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('char_equips',
    sa.Column('close_weapon_url', sa.Integer(), nullable=False),
    sa.Column('range_weapon_url', sa.Integer(), nullable=False),
    sa.Column('armor_url', sa.Integer(), nullable=False),
    sa.Column('ring_1_url', sa.Integer(), nullable=False),
    sa.Column('ring_2_url', sa.Integer(), nullable=False),
    sa.Column('amulet_url', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_char_equips'))
    )
    op.create_table('inventory',
    sa.Column('available_slots', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory'))
    )
    op.create_table('meta',
    sa.Column('story_delay', sa.Integer(), nullable=False),
    sa.Column('story_room_path', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meta'))
    )
    op.create_table('mobs',
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('weapon_url', sa.String(), nullable=False),
    sa.Column('armor_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('lvl', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('mana', sa.Integer(), nullable=False),
    sa.Column('actions', sa.Integer(), nullable=False),
    sa.Column('actions_max', sa.Integer(), nullable=False),
    sa.Column('bonus_actions', sa.Integer(), nullable=False),
    sa.Column('bonus_actions_max', sa.Integer(), nullable=False),
    sa.Column('prepared_spell_1_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_2_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_3_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_4_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_5_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_6_id', sa.Integer(), nullable=True),
    sa.Column('available_spells', sa.Integer(), nullable=False),
    sa.Column('stat_strength', sa.Integer(), nullable=False),
    sa.Column('stat_dexterity', sa.Integer(), nullable=False),
    sa.Column('stat_constitution', sa.Integer(), nullable=False),
    sa.Column('stat_intelligence', sa.Integer(), nullable=False),
    sa.Column('stat_will', sa.Integer(), nullable=False),
    sa.Column('current_initiative', sa.Integer(), nullable=False),
    sa.Column('effects', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mobs'))
    )
    op.create_table('profiles',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=140), nullable=False),
    sa.Column('last_ip', sa.String(), nullable=False),
    sa.Column('first_game_id', sa.Integer(), nullable=True),
    sa.Column('second_game_id', sa.Integer(), nullable=True),
    sa.Column('third_game_id', sa.Integer(), nullable=True),
    sa.Column('active_game_id', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    op.create_table('raids',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('current_line', sa.Integer(), nullable=False),
    sa.Column('mesh', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raids'))
    )
    op.create_table('roll',
    sa.Column('d2', sa.Integer(), nullable=True),
    sa.Column('d4', sa.Integer(), nullable=True),
    sa.Column('d6', sa.Integer(), nullable=True),
    sa.Column('d8', sa.Integer(), nullable=True),
    sa.Column('d10', sa.Integer(), nullable=True),
    sa.Column('d12', sa.Integer(), nullable=True),
    sa.Column('d20', sa.Integer(), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roll'))
    )
    op.create_table('rooms',
    sa.Column('room_type', sa.String(), nullable=False),
    sa.Column('room_path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text_pointer', sa.Integer(), nullable=False),
    sa.Column('texts', sa.JSON(), nullable=False),
    sa.Column('stoppers', sa.JSON(), nullable=False),
    sa.Column('next_state', sa.String(), nullable=False),
    sa.Column('updated_states', sa.JSON(), nullable=False),
    sa.Column('enemies', sa.JSON(), nullable=False),
    sa.Column('loot', sa.JSON(), nullable=False),
    sa.Column('can_exit', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rooms'))
    )
    op.create_table('world',
    sa.Column('raid_goblin_forest_available', sa.Boolean(), nullable=False),
    sa.Column('raid_empire_caves', sa.Boolean(), nullable=False),
    sa.Column('raid_elven_ruins', sa.Boolean(), nullable=False),
    sa.Column('raid_tropical_islands', sa.Boolean(), nullable=False),
    sa.Column('raid_dead_city', sa.Boolean(), nullable=False),
    sa.Column('trader_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_world'))
    )
    op.create_table('ip_associations',
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_ip_associations_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ip_associations')),
    sa.UniqueConstraint('ip_address', name=op.f('uq_ip_associations_ip_address'))
    )
    op.create_table('main_characters',
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('max_energy', sa.Float(), nullable=False),
    sa.Column('energy_per_minute', sa.Float(), nullable=False),
    sa.Column('char_equip_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('lvl', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('mana', sa.Integer(), nullable=False),
    sa.Column('actions', sa.Integer(), nullable=False),
    sa.Column('actions_max', sa.Integer(), nullable=False),
    sa.Column('bonus_actions', sa.Integer(), nullable=False),
    sa.Column('bonus_actions_max', sa.Integer(), nullable=False),
    sa.Column('prepared_spell_1_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_2_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_3_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_4_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_5_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_6_id', sa.Integer(), nullable=True),
    sa.Column('available_spells', sa.Integer(), nullable=False),
    sa.Column('stat_strength', sa.Integer(), nullable=False),
    sa.Column('stat_dexterity', sa.Integer(), nullable=False),
    sa.Column('stat_constitution', sa.Integer(), nullable=False),
    sa.Column('stat_intelligence', sa.Integer(), nullable=False),
    sa.Column('stat_will', sa.Integer(), nullable=False),
    sa.Column('current_initiative', sa.Integer(), nullable=False),
    sa.Column('effects', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['char_equip_id'], ['char_equips.id'], name=op.f('fk_main_characters_char_equip_id_char_equips'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('fk_main_characters_inventory_id_inventory'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_main_characters'))
    )
    op.create_table('games',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('major_state', sa.String(), nullable=True),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('raid_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('meta_id', sa.Integer(), nullable=False),
    sa.Column('roll_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['main_characters.id'], name=op.f('fk_games_character_id_main_characters'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['meta_id'], ['meta.id'], name=op.f('fk_games_meta_id_meta'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raid_id'], ['raids.id'], name=op.f('fk_games_raid_id_raids'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['roll_id'], ['roll.id'], name=op.f('fk_games_roll_id_roll'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_games_room_id_rooms'), onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], name=op.f('fk_games_world_id_world'), onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('main_characters')
    op.drop_table('ip_associations')
    op.drop_table('world')
    op.drop_table('rooms')
    op.drop_table('roll')
    op.drop_table('raids')
    op.drop_table('profiles')
    op.drop_table('mobs')
    op.drop_table('meta')
    op.drop_table('inventory')
    op.drop_table('char_equips')
    # ### end Alembic commands ###
