"""update roll table coluns to list

Revision ID: 39ac0fdba57a
Revises: 383497a7ec70
Create Date: 2026-05-24 06:15:44.491758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ac0fdba57a'
down_revision: Union[str, Sequence[str], None] = '383497a7ec70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roll', schema=None) as batch_op:
        batch_op.alter_column('d2',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('d4',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('d6',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('d8',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('d10',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('d12',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('d20',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               nullable=False)
        batch_op.alter_column('percent',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roll', schema=None) as batch_op:
        batch_op.alter_column('percent',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('d20',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('d12',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('d10',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('d8',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('d6',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('d4',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('d2',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
