"""add loot and exp to mobs table

Revision ID: b9e834ab1232
Revises: 38b0b4671e28
Create Date: 2026-06-09 02:53:28.128421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e834ab1232'
down_revision: Union[str, Sequence[str], None] = '38b0b4671e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exp', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('loot', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.drop_column('loot')
        batch_op.drop_column('exp')

    # ### end Alembic commands ###
