"""add mana_max column to char tables

Revision ID: f92829a8feb4
Revises: e724b498934b
Create Date: 2026-05-27 14:45:15.072104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92829a8feb4'
down_revision: Union[str, Sequence[str], None] = 'e724b498934b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mana_max', sa.Integer(), nullable=False))

    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mana_max', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.drop_column('mana_max')

    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.drop_column('mana_max')

    # ### end Alembic commands ###
