"""add scripts column to char tables

Revision ID: 4a6499f7b42d
Revises: f92829a8feb4
Create Date: 2026-05-28 11:02:36.653146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6499f7b42d'
down_revision: Union[str, Sequence[str], None] = 'f92829a8feb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scripts', sa.JSON(), nullable=False))

    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scripts', sa.JSON(), nullable=False))


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.drop_column('scripts')

    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.drop_column('scripts')

    # ### end Alembic commands ###
