"""rename next_state column to state rooms table

Revision ID: 38b0b4671e28
Revises: 34b1aa9e10a6
Create Date: 2026-05-30 10:08:12.216209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b0b4671e28'
down_revision: Union[str, Sequence[str], None] = '34b1aa9e10a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(), nullable=False))
        batch_op.drop_column('next_state')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_state', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('state')

    # ### end Alembic commands ###
