"""add back_url column to roll table

Revision ID: 34b1aa9e10a6
Revises: 4a6499f7b42d
Create Date: 2026-05-29 18:07:31.162870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34b1aa9e10a6'
down_revision: Union[str, Sequence[str], None] = '4a6499f7b42d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roll', schema=None) as batch_op:
        batch_op.add_column(sa.Column('back_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roll', schema=None) as batch_op:
        batch_op.drop_column('back_url')

    # ### end Alembic commands ###
