"""update tables

Revision ID: 27fbf31fed83
Revises: aa7863d67b9a
Create Date: 2026-05-11 07:35:41.253906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27fbf31fed83'
down_revision: Union[str, Sequence[str], None] = 'aa7863d67b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('major_state',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('world_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('raid_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('raids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=False))
        batch_op.alter_column('current_room',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('all_rooms',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('game_id')

    with op.batch_alter_table('raids', schema=None) as batch_op:
        batch_op.alter_column('all_rooms',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('current_room',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('game_id')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('raid_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('world_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('major_state',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
