"""add roll table

Revision ID: c2ac839ea9b9
Revises: a5a2e1bb1385
Create Date: 2026-05-19 22:50:45.800576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ac839ea9b9'
down_revision: Union[str, Sequence[str], None] = 'a5a2e1bb1385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roll',
    sa.Column('d2', sa.Integer(), nullable=True),
    sa.Column('d4', sa.Integer(), nullable=True),
    sa.Column('d6', sa.Integer(), nullable=True),
    sa.Column('d8', sa.Integer(), nullable=True),
    sa.Column('d10', sa.Integer(), nullable=True),
    sa.Column('d12', sa.Integer(), nullable=True),
    sa.Column('d20', sa.Integer(), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roll_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_game_roll", 'roll', ['roll_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint("fk_game_roll", type_='foreignkey')
        batch_op.drop_column('roll_id')

    op.drop_table('roll')
    # ### end Alembic commands ###
