"""update table name to plural

Revision ID: d78071c551de
Revises: 1b172a51cb21
Create Date: 2026-05-08 04:19:15.217351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78071c551de'
down_revision: Union[str, Sequence[str], None] = '1b172a51cb21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('major_state_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=140), nullable=False),
    sa.Column('last_ip', sa.String(), nullable=False),
    sa.Column('first_game_id', sa.Integer(), nullable=True),
    sa.Column('second_game_id', sa.Integer(), nullable=True),
    sa.Column('third_game_id', sa.Integer(), nullable=True),
    sa.Column('active_game_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game')
    op.drop_table('profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('password', sa.VARCHAR(length=140), nullable=False),
    sa.Column('last_ip', sa.VARCHAR(), nullable=False),
    sa.Column('first_game_id', sa.INTEGER(), nullable=True),
    sa.Column('second_game_id', sa.INTEGER(), nullable=True),
    sa.Column('third_game_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('active_game_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('character_id', sa.INTEGER(), nullable=False),
    sa.Column('major_state_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('profiles')
    op.drop_table('games')
    # ### end Alembic commands ###
