"""update relationships between ip_associations and profiles

Revision ID: ed8af52a8d20
Revises: d78071c551de
Create Date: 2026-05-08 04:29:57.305029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8af52a8d20'
down_revision: Union[str, Sequence[str], None] = 'd78071c551de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_associations', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_ip_assoc_profile", 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_associations', schema=None) as batch_op:
        batch_op.drop_constraint("fk_ip_assoc_profile", type_='foreignkey')

    # ### end Alembic commands ###
