"""add action and bonus_action to chars tables

Revision ID: 9fad17b854df
Revises: 354e0304da27
Create Date: 2026-05-19 21:14:54.605833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fad17b854df'
down_revision: Union[str, Sequence[str], None] = '354e0304da27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('actions_max', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bonus_actions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bonus_actions_max', sa.Integer(), nullable=False))

    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('actions_max', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bonus_actions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bonus_actions_max', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.drop_column('bonus_actions_max')
        batch_op.drop_column('bonus_actions')
        batch_op.drop_column('actions_max')
        batch_op.drop_column('actions')

    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.drop_column('bonus_actions_max')
        batch_op.drop_column('bonus_actions')
        batch_op.drop_column('actions_max')
        batch_op.drop_column('actions')

    # ### end Alembic commands ###
