"""update type to room_type

Revision ID: 46122eb79ef5
Revises: 5157945ad7f0
Create Date: 2026-05-16 19:39:56.362667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46122eb79ef5'
down_revision: Union[str, Sequence[str], None] = '5157945ad7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_type', sa.String(), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('room_type')

    # ### end Alembic commands ###
