"""update room table

Revision ID: f7ee3f5f9d4c
Revises: 4c89a0f49d3f
Create Date: 2026-05-13 13:56:21.696756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ee3f5f9d4c'
down_revision: Union[str, Sequence[str], None] = '4c89a0f49d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('local_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('values', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('loot', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('can_exit', sa.Boolean(), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('desc')
        batch_op.drop_column('can_free_exit')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_free_exit', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('desc', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('can_exit')
        batch_op.drop_column('loot')
        batch_op.drop_column('values')
        batch_op.drop_column('local_state')
        batch_op.drop_column('room_path')

    # ### end Alembic commands ###
