"""update relationships and possible values

Revision ID: cd5e023ac9eb
Revises: 152ba15db31b
Create Date: 2026-05-13 18:10:36.142326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cd5e023ac9eb'
down_revision: Union[str, Sequence[str], None] = '152ba15db31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('world_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('raid_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('raid_meta_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.alter_column('max_energy',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('char_equip_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('inventory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('effects',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.create_foreign_key("fk_games_inventory", 'inventory', ['inventory_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key("fk_games_char_equips", 'char_equips', ['char_equip_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.alter_column('effects',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('raids', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('desc',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('current_room',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('mesh',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('local_state',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('values',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('loot',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('can_exit',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('can_exit',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('loot',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('values',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('local_state',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('raids', schema=None) as batch_op:
        batch_op.alter_column('mesh',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('current_room',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('desc',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.alter_column('effects',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.drop_constraint("fk_games_inventory", type_='foreignkey')
        batch_op.drop_constraint("fk_games_char_equips", type_='foreignkey')
        batch_op.alter_column('effects',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('inventory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('char_equip_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_energy',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('raid_meta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('raid_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('world_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('character_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
