"""create game character tables

Revision ID: 751514adee2f
Revises: dfbdb523c359
Create Date: 2026-05-10 05:40:55.435438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751514adee2f'
down_revision: Union[str, Sequence[str], None] = 'dfbdb523c359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_characters',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('mana', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('energy_per_minute', sa.Float(), nullable=False),
    sa.Column('prepared_spell_1_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_2_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_3_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_4_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_5_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_6_id', sa.Integer(), nullable=True),
    sa.Column('available_spells', sa.Integer(), nullable=False),
    sa.Column('characteristic_strength', sa.Integer(), nullable=False),
    sa.Column('characteristic_dexterity', sa.Integer(), nullable=False),
    sa.Column('characteristic_constitution', sa.Integer(), nullable=False),
    sa.Column('characteristic_intelligence', sa.Integer(), nullable=False),
    sa.Column('characteristic_will', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mob_characters',
    sa.Column('mob_name', sa.String(), nullable=False),
    sa.Column('mob_desc', sa.String(), nullable=False),
    sa.Column('min_hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('min_mana', sa.Integer(), nullable=False),
    sa.Column('max_mana', sa.Integer(), nullable=False),
    sa.Column('prepared_spell_1_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_2_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_3_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_4_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_5_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_6_id', sa.Integer(), nullable=True),
    sa.Column('available_spells', sa.Integer(), nullable=False),
    sa.Column('characteristic_strength', sa.Integer(), nullable=False),
    sa.Column('characteristic_dexterity', sa.Integer(), nullable=False),
    sa.Column('characteristic_constitution', sa.Integer(), nullable=False),
    sa.Column('characteristic_intelligence', sa.Integer(), nullable=False),
    sa.Column('characteristic_will', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mob_characters')
    op.drop_table('main_characters')
    # ### end Alembic commands ###
