"""add to ip_associations available none field for profile_id

Revision ID: dfbdb523c359
Revises: ed8af52a8d20
Create Date: 2026-05-08 08:34:57.167362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbdb523c359'
down_revision: Union[str, Sequence[str], None] = 'ed8af52a8d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_associations', schema=None) as batch_op:
        batch_op.alter_column('profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_associations', schema=None) as batch_op:
        batch_op.alter_column('profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
