"""add raid_mesh column in raids table

Revision ID: 4c89a0f49d3f
Revises: 161410ebb43c
Create Date: 2026-05-13 09:19:34.581595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c89a0f49d3f'
down_revision: Union[str, Sequence[str], None] = '161410ebb43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mesh', sa.JSON(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('all_rooms')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('all_rooms', sa.INTEGER(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('mesh')
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
