"""add weapon_url to mob table

Revision ID: b919c7db489c
Revises: 9fad17b854df
Create Date: 2026-05-19 21:20:06.564298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b919c7db489c'
down_revision: Union[str, Sequence[str], None] = '9fad17b854df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weapon_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.drop_column('weapon_url')

    # ### end Alembic commands ###
