"""active_game_id replaces from ip_associations to profile

Revision ID: 1b172a51cb21
Revises: c99daf4fe210
Create Date: 2026-05-08 04:07:49.590261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b172a51cb21'
down_revision: Union[str, Sequence[str], None] = 'c99daf4fe210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_associations', 'active_game_id')
    op.add_column('profile', sa.Column('active_game_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'active_game_id')
    op.add_column('ip_associations', sa.Column('active_game_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
