"""update relationships

Revision ID: a3915a6b3a5d
Revises: ffc5a1947e04
Create Date: 2026-05-11 17:05:43.120216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3915a6b3a5d'
down_revision: Union[str, Sequence[str], None] = 'ffc5a1947e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_main_characters_games'), type_='foreignkey')
        batch_op.drop_column('game_id')

    with op.batch_alter_table('raids', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_raids_games'), type_='foreignkey')
        batch_op.drop_column('game_id')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rooms_games'), type_='foreignkey')
        batch_op.drop_column('game_id')

    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_world_games'), type_='foreignkey')
        batch_op.drop_column('game_id')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('world_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('raid_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_world_games", 'world', ['world_id'], ['id'], onupdate='CASCADE')
        batch_op.create_foreign_key("fk_raids_games", 'raids', ['raid_id'], ['id'], onupdate='CASCADE')
        batch_op.create_foreign_key("fk_main_characters_games", 'main_characters', ['character_id'], ['id'], onupdate='CASCADE')
        batch_op.create_foreign_key("fk_rooms_games", 'rooms', ['room_id'], ['id'], onupdate='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint("fk_main_characters_games", type_='foreignkey')
        batch_op.drop_constraint("fk_world_games", type_='foreignkey')
        batch_op.drop_constraint("fk_raids_games", type_='foreignkey')
        batch_op.drop_constraint("fk_rooms_games", type_='foreignkey')
        batch_op.drop_column('room_id')
        batch_op.drop_column('raid_id')
        batch_op.drop_column('world_id')
        batch_op.drop_column('character_id')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_world_games'), 'games', ['game_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_rooms_games'), 'games', ['game_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('raids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_raids_games'), 'games', ['game_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_main_characters_games'), 'games', ['game_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
