"""rename raid types in world_model table

Revision ID: 354e0304da27
Revises: 46122eb79ef5
Create Date: 2026-05-17 23:43:55.144058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354e0304da27'
down_revision: Union[str, Sequence[str], None] = '46122eb79ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raid_goblin_forest_available', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('raid_empire_caves', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('raid_elven_ruins', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('raid_tropical_islands', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('raid_dead_city', sa.Boolean(), nullable=False))
        batch_op.drop_column('raid_3_available')
        batch_op.drop_column('raid_1_available')
        batch_op.drop_column('raid_5_available')
        batch_op.drop_column('raid_2_available')
        batch_op.drop_column('raid_4_available')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raid_4_available', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('raid_2_available', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('raid_5_available', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('raid_1_available', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('raid_3_available', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('raid_dead_city')
        batch_op.drop_column('raid_tropical_islands')
        batch_op.drop_column('raid_elven_ruins')
        batch_op.drop_column('raid_empire_caves')
        batch_op.drop_column('raid_goblin_forest_available')

    # ### end Alembic commands ###
