"""update characters tables

Revision ID: 1d54829aff04
Revises: e4fc096b72a0
Create Date: 2026-05-11 06:46:32.488242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d54829aff04'
down_revision: Union[str, Sequence[str], None] = 'e4fc096b72a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobs',
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('lvl', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('mana', sa.Integer(), nullable=False),
    sa.Column('prepared_spell_1_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_2_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_3_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_4_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_5_id', sa.Integer(), nullable=True),
    sa.Column('prepared_spell_6_id', sa.Integer(), nullable=True),
    sa.Column('available_spells', sa.Integer(), nullable=False),
    sa.Column('characteristic_strength', sa.Integer(), nullable=False),
    sa.Column('characteristic_dexterity', sa.Integer(), nullable=False),
    sa.Column('characteristic_constitution', sa.Integer(), nullable=False),
    sa.Column('characteristic_intelligence', sa.Integer(), nullable=False),
    sa.Column('characteristic_will', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mob_characters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mob_characters',
    sa.Column('min_hp', sa.INTEGER(), nullable=False),
    sa.Column('max_hp', sa.INTEGER(), nullable=False),
    sa.Column('min_mana', sa.INTEGER(), nullable=False),
    sa.Column('max_mana', sa.INTEGER(), nullable=False),
    sa.Column('prepared_spell_1_id', sa.INTEGER(), nullable=True),
    sa.Column('prepared_spell_2_id', sa.INTEGER(), nullable=True),
    sa.Column('prepared_spell_3_id', sa.INTEGER(), nullable=True),
    sa.Column('prepared_spell_4_id', sa.INTEGER(), nullable=True),
    sa.Column('prepared_spell_5_id', sa.INTEGER(), nullable=True),
    sa.Column('prepared_spell_6_id', sa.INTEGER(), nullable=True),
    sa.Column('available_spells', sa.INTEGER(), nullable=False),
    sa.Column('characteristic_strength', sa.INTEGER(), nullable=False),
    sa.Column('characteristic_dexterity', sa.INTEGER(), nullable=False),
    sa.Column('characteristic_constitution', sa.INTEGER(), nullable=False),
    sa.Column('characteristic_intelligence', sa.INTEGER(), nullable=False),
    sa.Column('characteristic_will', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('desc', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('lvl', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mobs')
    # ### end Alembic commands ###
