"""rename characteristic to stat in chars tables

Revision ID: ff1f29536906
Revises: 9d45b8fb89ee
Create Date: 2026-05-23 06:13:53.127683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1f29536906'
down_revision: Union[str, Sequence[str], None] = '9d45b8fb89ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stat_strength', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stat_dexterity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stat_constitution', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stat_intelligence', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stat_will', sa.Integer(), nullable=False))
        batch_op.drop_column('characteristic_intelligence')
        batch_op.drop_column('characteristic_will')
        batch_op.drop_column('characteristic_constitution')
        batch_op.drop_column('characteristic_dexterity')
        batch_op.drop_column('characteristic_strength')

    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stat_strength', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stat_dexterity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stat_constitution', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stat_intelligence', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('stat_will', sa.Integer(), nullable=False))
        batch_op.drop_column('characteristic_intelligence')
        batch_op.drop_column('characteristic_will')
        batch_op.drop_column('characteristic_constitution')
        batch_op.drop_column('characteristic_dexterity')
        batch_op.drop_column('characteristic_strength')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characteristic_strength', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('characteristic_dexterity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('characteristic_constitution', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('characteristic_will', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('characteristic_intelligence', sa.INTEGER(), nullable=False))
        batch_op.drop_column('stat_will')
        batch_op.drop_column('stat_intelligence')
        batch_op.drop_column('stat_constitution')
        batch_op.drop_column('stat_dexterity')
        batch_op.drop_column('stat_strength')

    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characteristic_strength', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('characteristic_dexterity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('characteristic_constitution', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('characteristic_will', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('characteristic_intelligence', sa.INTEGER(), nullable=False))
        batch_op.drop_column('stat_will')
        batch_op.drop_column('stat_intelligence')
        batch_op.drop_column('stat_constitution')
        batch_op.drop_column('stat_dexterity')
        batch_op.drop_column('stat_strength')

    # ### end Alembic commands ###
