"""update main_character columns

Revision ID: 152ba15db31b
Revises: e2d2072db721
Create Date: 2026-05-13 17:05:02.652455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152ba15db31b'
down_revision: Union[str, Sequence[str], None] = 'e2d2072db721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effects', sa.JSON(), nullable=True))

    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effects', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.drop_column('effects')

    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.drop_column('effects')

    # ### end Alembic commands ###
