"""update world table

Revision ID: 2a5f4e9391f6
Revises: 1d54829aff04
Create Date: 2026-05-11 06:49:51.197580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a5f4e9391f6'
down_revision: Union[str, Sequence[str], None] = '1d54829aff04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raid_1_available', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('raid_2_available', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('raid_3_available', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('raid_4_available', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('raid_5_available', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('trader_available', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('world', schema=None) as batch_op:
        batch_op.drop_column('trader_available')
        batch_op.drop_column('raid_5_available')
        batch_op.drop_column('raid_4_available')
        batch_op.drop_column('raid_3_available')
        batch_op.drop_column('raid_2_available')
        batch_op.drop_column('raid_1_available')

    # ### end Alembic commands ###
