"""remame column from current_room to current_line

Revision ID: 327cc7a441f2
Revises: cd5e023ac9eb
Create Date: 2026-05-13 19:15:03.280387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327cc7a441f2'
down_revision: Union[str, Sequence[str], None] = 'cd5e023ac9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_line', sa.Integer(), nullable=False))
        batch_op.drop_column('current_room')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_room', sa.INTEGER(), nullable=False))
        batch_op.drop_column('current_line')

    # ### end Alembic commands ###
