"""update raid_meta

Revision ID: 161410ebb43c
Revises: c01059b463a7
Create Date: 2026-05-12 13:27:00.126163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '161410ebb43c'
down_revision: Union[str, Sequence[str], None] = 'c01059b463a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raid_meta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('story_room_path', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raid_meta', schema=None) as batch_op:
        batch_op.drop_column('story_room_path')

    # ### end Alembic commands ###
