"""add columns name and state_texts to rooms table

Revision ID: 9d45b8fb89ee
Revises: c2ac839ea9b9
Create Date: 2026-05-21 04:44:28.505993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d45b8fb89ee'
down_revision: Union[str, Sequence[str], None] = 'c2ac839ea9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('state_texts', sa.JSON(), nullable=False))
        batch_op.alter_column('room_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('room_path',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('room_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('room_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('state_texts')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
