"""create raid_meta table

Revision ID: c01059b463a7
Revises: a3915a6b3a5d
Create Date: 2026-05-12 13:13:08.994252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01059b463a7'
down_revision: Union[str, Sequence[str], None] = 'a3915a6b3a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raid_meta_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_games_raid_meta", 'raid_meta', ['raid_meta_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint("fk_games_raid_meta", type_='foreignkey')
        batch_op.drop_column('raid_meta_id')

    # ### end Alembic commands ###
