"""returning tables

Revision ID: c99daf4fe210
Revises: 3c9be87207f2
Create Date: 2026-05-08 03:46:06.776836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99daf4fe210'
down_revision: Union[str, Sequence[str], None] = '3c9be87207f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_associations',
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('active_game_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('profile',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=140), nullable=False),
    sa.Column('last_ip', sa.String(), nullable=False),
    sa.Column('first_game_id', sa.Integer(), nullable=True),
    sa.Column('second_game_id', sa.Integer(), nullable=True),
    sa.Column('third_game_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ip_associations_')
    op.drop_table('profile_')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_',
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('password', sa.VARCHAR(length=140), nullable=False),
    sa.Column('last_ip', sa.VARCHAR(), nullable=False),
    sa.Column('first_game_id', sa.INTEGER(), nullable=True),
    sa.Column('second_game_id', sa.INTEGER(), nullable=True),
    sa.Column('third_game_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_associations_',
    sa.Column('ip_address', sa.VARCHAR(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=False),
    sa.Column('active_game_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.drop_table('profile')
    op.drop_table('ip_associations')
    # ### end Alembic commands ###
