"""rename item link columns from id to url

Revision ID: a5a2e1bb1385
Revises: b919c7db489c
Create Date: 2026-05-19 21:22:58.248677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a2e1bb1385'
down_revision: Union[str, Sequence[str], None] = 'b919c7db489c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('char_equips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_weapon_url', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('range_weapon_url', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('armor_url', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ring_1_url', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ring_2_url', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('amulet_url', sa.Integer(), nullable=False))
        batch_op.drop_column('armor_id')
        batch_op.drop_column('range_weapon_id')
        batch_op.drop_column('amulet_id')
        batch_op.drop_column('ring_1_id')
        batch_op.drop_column('ring_2_id')
        batch_op.drop_column('close_weapon_id')

    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('armor_url', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.drop_column('armor_url')

    with op.batch_alter_table('char_equips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_weapon_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ring_2_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ring_1_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('amulet_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('range_weapon_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('armor_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('amulet_url')
        batch_op.drop_column('ring_2_url')
        batch_op.drop_column('ring_1_url')
        batch_op.drop_column('armor_url')
        batch_op.drop_column('range_weapon_url')
        batch_op.drop_column('close_weapon_url')

    # ### end Alembic commands ###
