"""update characterds table

Revision ID: c1b92686c378
Revises: 6978bbba7c4b
Create Date: 2026-05-10 11:27:02.461745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b92686c378'
down_revision: Union[str, Sequence[str], None] = '6978bbba7c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lvl', sa.Integer(), nullable=False))

    with op.batch_alter_table('mob_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lvl', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mob_characters', schema=None) as batch_op:
        batch_op.drop_column('lvl')

    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.drop_column('lvl')

    # ### end Alembic commands ###
