"""update profile table

Revision ID: 985f644355f4
Revises: 1047d5c49a2c
Create Date: 2026-05-07 12:14:11.656778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985f644355f4'
down_revision: Union[str, Sequence[str], None] = '1047d5c49a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('first_game_id', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('second_game_id', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('third_game_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'third_game_id')
    op.drop_column('profile', 'second_game_id')
    op.drop_column('profile', 'first_game_id')
    # ### end Alembic commands ###
