"""rename columg raid_meta_id to meta_id in games table

Revision ID: 10e11fd64ea0
Revises: 758567423e07
Create Date: 2026-05-23 10:27:06.015529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e11fd64ea0'
down_revision: Union[str, Sequence[str], None] = '758567423e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE games RENAME COLUMN raid_meta_id TO meta_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
