"""add initiative column to chars tables

Revision ID: 5e09f72907e9
Revises: ff1f29536906
Create Date: 2026-05-23 06:32:06.017628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e09f72907e9'
down_revision: Union[str, Sequence[str], None] = 'ff1f29536906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_initiative', sa.Integer(), nullable=False))

    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_initiative', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mobs', schema=None) as batch_op:
        batch_op.drop_column('current_initiative')

    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.drop_column('current_initiative')

    # ### end Alembic commands ###
