"""create inventory and char_equip tables

Revision ID: e2d2072db721
Revises: f7ee3f5f9d4c
Create Date: 2026-05-13 16:55:39.077347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d2072db721'
down_revision: Union[str, Sequence[str], None] = 'f7ee3f5f9d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('char_equips',
    sa.Column('close_weapon_id', sa.Integer(), nullable=True),
    sa.Column('range_weapon_id', sa.Integer(), nullable=True),
    sa.Column('armor_id', sa.Integer(), nullable=True),
    sa.Column('ring_1_id', sa.Integer(), nullable=True),
    sa.Column('ring_2_id', sa.Integer(), nullable=True),
    sa.Column('amulet_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('available_slots', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('char_equips')
    # ### end Alembic commands ###
