"""update character tables columns

Revision ID: 6978bbba7c4b
Revises: e04b498def20
Create Date: 2026-05-10 07:19:54.737552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6978bbba7c4b'
down_revision: Union[str, Sequence[str], None] = 'e04b498def20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))

    with op.batch_alter_table('mob_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.drop_column('mob_name')
        batch_op.drop_column('mob_desc')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mob_characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mob_desc', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('mob_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('desc')

    with op.batch_alter_table('main_characters', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
