"""update game table to static world, raid, room

Revision ID: aa7863d67b9a
Revises: 2a5f4e9391f6
Create Date: 2026-05-11 07:03:49.300907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7863d67b9a'
down_revision: Union[str, Sequence[str], None] = '2a5f4e9391f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major_state', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('world_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('raid_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=False))
        batch_op.drop_column('major_state_id')
        batch_op.drop_column('major_object_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major_object_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('major_state_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('room_id')
        batch_op.drop_column('raid_id')
        batch_op.drop_column('world_id')
        batch_op.drop_column('major_state')

    # ### end Alembic commands ###
