"""remane table from ip_to_profile to ip_associations

Revision ID: 21a869780c67
Revises: 985f644355f4
Create Date: 2026-05-08 03:02:12.080443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a869780c67'
down_revision: Union[str, Sequence[str], None] = '985f644355f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_associations',
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('active_game_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ip_to_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_to_profile',
    sa.Column('ip_address', sa.VARCHAR(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=False),
    sa.Column('active_game_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ip_associations')
    # ### end Alembic commands ###
