"""update profile table add permissions column

Revision ID: 5157945ad7f0
Revises: 327cc7a441f2
Create Date: 2026-05-15 12:45:25.095503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5157945ad7f0'
down_revision: Union[str, Sequence[str], None] = '327cc7a441f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.String(), nullable=False))

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enemies', sa.JSON(), nullable=False))
        batch_op.drop_column('values')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('values', sqlite.JSON(), nullable=False))
        batch_op.drop_column('enemies')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###
